# Generated by Django 3.1.2 on 2020-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='poop'),
            preserve_default=False,
        ),
    ]
